# Rest client extention vs code should downloaded 
# File name must be .http extention and in backend folder


@userHost = http://localhost:9000/api/v1/user
@jobHost = http://localhost:9000/api/v1/job
@companyHost = http://localhost:9000/api/v1/company
@applicationHost = http://localhost:9000/api/v1/application



### -----------------User----------------------
POST {{userHost}}/register
Content-Type: application/json

{
  "fullname": "Vijay",
  "email": "vijay@gmail.com",
  "phoneNumber": "7763949572",
  "password": "vijay@123",
  "role": "Recruiter"
}

###
POST {{userHost}}/register
Content-Type: application/json

{
  "fullname": "Kumar",
  "email": "kumar@gmail.com",
  "phoneNumber": "7763949572",
  "password": "kumar@123",
  "role": "Student"
}

###

POST {{userHost}}/login
Content-Type: application/json

{
  "email": "vijay@gmail.com",
  "password": "vijay@123",
  "role": "Recruiter"
}

###

POST {{userHost}}/login
Content-Type: application/json

{
  "email": "kumar@gmail.com",
  "password": "kumar@123",
  "role": "Student"
}

###

POST {{userHost}}/profile/update
Content-Type: application/json

{
  "fullname": "Vijay"
}

###

GET {{userHost}}/logout


### ---------------Company-------------------

POST {{companyHost}}/register
Content-Type: application/json

{
  "companyName": "testing company"
}

###

GET {{companyHost}}/get

###

GET {{companyHost}}/get/6782aa08d72153cf93311614


### 
PUT {{companyHost}}/update/678387e2346d7620fedc63a9
Content-Type: application/json

{
  "name": "Vijay Company tech"
}

###----------jobRoute by admin and user also

POST {{jobHost}}/post
Content-Type: application/json

{
  "title": "backend developer",
  "description": "I want backend developer for my comnany",
  "requirements": "React js, Shadcn ui, Api Testing",
  "salary": "12",
  "location": "Hydrabad",
  "jobType": "Full Time",
  "position": 12,
  "experience": 1,
  "companyId": "6782a6a91c79f0ae08afb40b"
}


###

GET {{jobHost}}/get

###
GET {{jobHost}}/getadminjobs

### 
GET {{jobHost}}/get/6783e9261a672a9b2f3f9786


###------------Application--------------------

GET {{applicationHost}}/apply/678659423f9ac4e586c42e33


### 
GET {{applicationHost}}/get

###
GET {{applicationHost}}/678659183f9ac4e586c42e2f/applicants

###
POST {{applicationHost}}/status/678692ba20527a0191cc5570/update
Content-Type: application/json

{
  "status": "Accepted"
}

