// Rest client extention vs code should downloaded 
// File name must be .http extention and in backend folder

@host = http://localhost:9000/api/v1/user

POST {{host}}/register
Content-Type: application/json

{
  "fullName": "Vijay",
  "email": "vijay@gmail.com",
  "phoneNumber": "7763949572",
  "password": "vijay@123",
  "role": "Recruiter"
}

###

POST {{host}}/login
Content-Type: application/json

{
  "email": "vijay@gmail.com",
  "password": "vijay@123",
  "role": "Recruiter"
}
